import { resolveProjectEnv } from "../../helpers/index.ts";
import { INTERNAL_APP_ENV_LIST } from "../../helpers/metadata.ts";
import { itIsJavaScriptIdentifier } from "../../helpers/utils.ts";

const BANNER_COMMENT = [
  "/**",
  " * This file is auto-generated by Envy.",
  " * Do not edit this file directly.",
  " *",
  " * It assumes the union of resolved env keys across development, staging, and production.",
  " * A key is required only when it exists in every environment.",
  " * A key is optional when it exists in some environments but not all of them.",
  " */",
].join("\n");

function renderPropertyName(key: string): string {
  return itIsJavaScriptIdentifier(key) ? key : JSON.stringify(key);
}

export function renderEnvTypeContent(cwd = process.cwd()): string {
  const envList = INTERNAL_APP_ENV_LIST.map((appEnv) => resolveProjectEnv({ appEnv, cwd }));
  const allKeys = [...new Set(envList.flatMap((env) => Object.keys(env)))].sort();
  const appEnvType = INTERNAL_APP_ENV_LIST.map((appEnv) => `'${appEnv}'`).join(" | ");

  const envProperties = allKeys
    .filter((key) => key !== "APP_ENV")
    .map((key) => {
      const isRequiredInEveryAppEnv = envList.every((env) => Object.hasOwn(env, key));
      const optionalMarker = isRequiredInEveryAppEnv ? "" : "?";

      return `    readonly ${renderPropertyName(key)}${optionalMarker}: string`;
    });

  return `${BANNER_COMMENT}

declare namespace NodeJS {
  interface ProcessEnv {
    readonly APP_ENV: ${appEnvType}
${envProperties.join("\n")}
  }
}
`;
}
